---
# playbook.yml
- name: 'Provision Image'
  hosts: default
  become: true

  tasks:
    - name: Enable EPEL Repository on CentOS 8
      dnf:
        name: epel-release
        state: latest
    - name: install Apache
      package:
        name: 'httpd'
        state: present
    - name: up to date for all packages
      dnf:
        name: '*'
        state: latest
